= Coqni Video player


---

== Features
* Video preview pictures
* Skip opening, ending

---

== Demo
Click the link below to find a simple demo

http://bestofcode.net/Applications/Awesome-Video-Player/html/[ℹ️ Start demo]

---

== Setup
1. Clone the repository and insert the files into your project.


==== Alternatively you can import the javascript source and it will automatically initialize the video player.

1. You can add the javascript by adding the following to your html:
`<script src="https://www.bestofcode.net/video-player/VideoPlayer.js">`

2. You also have to add the css:
`<link rel="stylesheet" href="https://www.bestofcode.net/video-player/VideoPlayer.js">`

3. Add a div to your project and add the class `player`.

4. Add `player-src` to the div and give the video url as value.

The document should look like this:

```html
<html>
  <head>
      <link rel="stylesheet" href="https://www.bestofcode.net/video-player/VideoPlayer.js">
      <title>Video Player Demo</title>
  </head>
  <body>
      <div class="player" player-src="../videos/sample.mp4"></div>
  </body>
  <script src="https://www.bestofcode.net/video-player/VideoPlayer.js">
</html>
```
5. Now on page-load `VideoPlayer.js` will iterate through the HTML and will generate a separate VideoPlayer for each `div` which was annotated as mentioned before.

---

## VideoJS

Maybe this will be replaced with videoJS

https://videojs.com/getting-started/#customize[VideoJS]

https://videojs.com/plugins/[Plugins]

* https://www.npmjs.com/package/videojs-contrib-quality-levels[Quality]
* https://www.npmjs.com/package/videojs-playlist[Autoplay]
* https://www.npmjs.com/package/@filmgardi/videojs-next-episode[Next Episode]

